import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// LBP Client (app/(client)/) uniquement — port 1:1 de la charte G2S V37
// (LBP_V9.9_Studio.html ligne 11 : Google Fonts Archivo + IBM Plex Mono ;
// ligne 68-69 : Archivo pour le corps ET les titres/boutons — remplace
// l'ancien split Plus Jakarta Sans/Inter, plus nécessaire puisque le
// prototype utilise désormais une seule police partout). N'affecte pas le
// Studio, qui garde Geist (--font-sans reste inchangé, voir globals.css).
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono-client",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${archivo.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
